name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-api-endpoint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.3

    - name: Install dependencies
      run: go mod tidy

    - name: Build and test the application in Docker
      run: |
        docker build -t rwapi-test -f Dockerfile.test .
        docker run rwapi-test
